In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('heart.csv')
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [3]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [5]:
df[(df.RestingBP>df.RestingBP.mean()+3*df.RestingBP.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
109,39,M,ATA,190,241,0,Normal,106,N,0.0,Up,0
241,54,M,ASY,200,198,0,Normal,142,Y,2.0,Flat,1
365,64,F,ASY,200,0,0,Normal,140,Y,1.0,Flat,1
399,61,M,NAP,200,0,1,ST,70,N,0.0,Flat,1
592,61,M,ASY,190,287,1,LVH,150,Y,2.0,Down,1
732,56,F,ASY,200,288,1,LVH,133,Y,4.0,Down,1
759,54,M,ATA,192,283,0,LVH,195,N,0.0,Up,1

In [7]:
df1 = df[(df.RestingBP<=df.RestingBP.mean()+3*df.RestingBP.std())]
df1.shape

(911, 12)

In [8]:
df[(df.Cholesterol>df.Cholesterol.mean()+3*df.Cholesterol.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
76,32,M,ASY,118,529,0,Normal,130,N,0.0,Flat,1
149,54,M,ASY,130,603,1,Normal,125,Y,1.0,Flat,1
616,67,F,NAP,115,564,0,LVH,160,N,1.6,Flat,0

In [14]:
df2 = df1[(df.Cholesterol<=df.Cholesterol.mean()+3*df.Cholesterol.std())]
df2.shape

C:\Users\CHUFESS\AppData\Local\Temp\ipykernel_8208\2555363055.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df1[(df.Cholesterol<=df.Cholesterol.mean()+3*df.Cholesterol.std())]

(908, 12)

In [15]:
df[(df.FastingBS>df.FastingBS.mean()+3*df.FastingBS.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [16]:
df[(df.MaxHR>df.MaxHR.mean()+3*df.MaxHR.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [17]:
df[(df.Oldpeak>df.Oldpeak.mean()+3*df.Oldpeak.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
166,50,M,ASY,140,231,0,ST,140,Y,5.0,Flat,1
702,59,M,TA,178,270,0,LVH,145,N,4.2,Down,0
771,55,M,ASY,140,217,0,Normal,111,Y,5.6,Down,1
791,51,M,ASY,140,298,0,Normal,122,Y,4.2,Flat,1
850,62,F,ASY,160,164,0,LVH,145,N,6.2,Down,1
900,58,M,ASY,114,318,0,ST,140,N,4.4,Down,1

In [19]:
df3 = df2[(df.Oldpeak<=df.Oldpeak.mean()+3*df.Oldpeak.std())]
df3.shape

C:\Users\CHUFESS\AppData\Local\Temp\ipykernel_8208\512153305.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3 = df2[(df.Oldpeak<=df.Oldpeak.mean()+3*df.Oldpeak.std())]

(902, 12)

In [20]:
df3.Sex.unique()

array(['M', 'F'], dtype=object)

In [21]:
df3.ChestPainType.unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [22]:
df3.RestingECG.unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [23]:
df3.ExerciseAngina.unique()

array(['N', 'Y'], dtype=object)

In [24]:
df3.ST_Slope.unique()

array(['Up', 'Flat', 'Down'], dtype=object)

#### I will create dictionaries for them except for Sex and ExerciseAngina which I'm gonna get dummies for

In [25]:
df4 = df3.copy()

In [26]:
df4.ChestPainType.replace({'ATA':1, 'NAP':2, 'ASY':3, 'TA':4}, inplace=True)

df4.RestingECG.replace({'Normal':1, 'ST':2, 'LVH':3}, inplace=True)

df4.ST_Slope.replace({'Up':1, 'Flat':2, 'Down':3}, inplace=True)

In [28]:
df4.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,1,140,289,0,1,172,N,0.0,1,0
1,49,F,2,160,180,0,1,156,N,1.0,2,1
2,37,M,1,130,283,0,2,98,N,0.0,1,0
3,48,F,3,138,214,0,1,108,Y,1.5,2,1
4,54,M,2,150,195,0,1,122,N,0.0,1,0

In [30]:
df5 = pd.get_dummies(df4, drop_first=True)
df5.head()

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,Oldpeak,ST_Slope,HeartDisease,Sex_M,ExerciseAngina_Y
0,40,1,140,289,0,1,172,0.0,1,0,1,0
1,49,2,160,180,0,1,156,1.0,2,1,0,0
2,37,1,130,283,0,2,98,0.0,1,0,1,0
3,48,3,138,214,0,1,108,1.5,2,1,0,1
4,54,2,150,195,0,1,122,0.0,1,0,1,0

In [33]:
X = df5.drop('HeartDisease', axis=1)
X.head()

,Age,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,Oldpeak,ST_Slope,Sex_M,ExerciseAngina_Y
0,40,1,140,289,0,1,172,0.0,1,1,0
1,49,2,160,180,0,1,156,1.0,2,0,0
2,37,1,130,283,0,2,98,0.0,1,1,0
3,48,3,138,214,0,1,108,1.5,2,0,1
4,54,2,150,195,0,1,122,0.0,1,1,0

In [35]:
y = df5.HeartDisease
y.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
scale = MinMaxScaler()

In [40]:
X_scaled = scale.fit_transform(X)
X_scaled

array([[0.24489796, 0.        , 0.75675676, ..., 0.        , 1.        ,
        0.        ],
       [0.42857143, 0.33333333, 0.86486486, ..., 0.5       , 0.        ,
        0.        ],
       [0.18367347, 0.        , 0.7027027 , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.59183673, 0.66666667, 0.7027027 , ..., 0.5       , 1.        ,
        1.        ],
       [0.59183673, 0.        , 0.7027027 , ..., 0.5       , 0.        ,
        0.        ],
       [0.20408163, 0.33333333, 0.74594595, ..., 0.        , 1.        ,
        0.        ]])

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, stratify=y, random_state=10)

### Using SVC alone

In [43]:
from sklearn.svm import SVC

In [44]:
svm = SVC()

In [45]:
svm.fit(X_train, y_train)

SVC()

In [52]:
svm.score(X_test, y_test)

0.8628318584070797

In [49]:
from sklearn.model_selection import cross_val_score

score = cross_val_score(SVC(), X, y, cv=5)
score.mean()

0.6906445672191528

### Using SVC with Bagging

In [50]:
from sklearn.ensemble import BaggingClassifier

In [51]:
BC = BaggingClassifier(
    base_estimator=SVC(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)

In [53]:
BC.fit(X_train, y_train)

BaggingClassifier(base_estimator=SVC(), max_samples=0.8, n_estimators=100,
                  oob_score=True, random_state=0)

In [54]:
BC.score(X_test, y_test)

0.8672566371681416

In [56]:
score = cross_val_score(BC, X,y, cv=5)

In [57]:
score.mean()

0.6850767341927564

### Using  Decision Tree alone

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
DTC = DecisionTreeClassifier()

In [61]:
DTC.fit(X_train, y_train)

DecisionTreeClassifier()

In [62]:
DTC.score(X_test, y_test)

0.8053097345132744

In [64]:
score = cross_val_score(DecisionTreeClassifier(), X,y, cv=5)
score.mean()

0.7405279312461632

### Using Decision Tree with Bagging

In [65]:
from sklearn.ensemble import BaggingClassifier

In [66]:
BC_DTC = BaggingClassifier(
    base_estimator=DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)

In [67]:
BC_DTC.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(), max_samples=0.8,
                  n_estimators=100, oob_score=True, random_state=0)

In [68]:
BC_DTC.score(X_test, y_test)

0.8539823008849557

In [69]:
score = cross_val_score(BC_DTC, X,y, cv=5)

In [70]:
score.mean()

0.8014671577655003